### ISSUE TITLE
MQTT Client ID is not available in RabbitMQ

### ISSUE THREAD

**Issue by tobych** [rabbitmq/rabbitmq-mqtt#11]
I'm no expert on MQTT or RabbitMQ, but it seems that a Client ID set in the client (I'm using the Mosquitto Python client) doesn't end up in RabbitMQ or in the client_properties from the management API. Perhaps my client isn't actually sending it correctly, but I thought I'd file this anyway in case my client is working correctly.

**Comment by freeunion1possible** [comment]
@tobych Any way to get the client id? It seems that the http api can not get it.

**Comment by tobych** [comment]
@freeunion1possible I've not looked at this stuff for a couple years, but see the commit referenced above. Also, which HTTP API are you referring to?

**Comment by freeunion1possible** [comment]
@tobych http://localhost:15672/api/connections

**Comment by michaelklishin** [comment]
This is not a discussion forum.
