### ISSUE TITLE
Consider providing a way to merge preconfigured propereties/headers to all published messages

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-mqtt#129]
We should be able to specify some options in config that allow us to enrich MQTT messages with some fields that are only supported by AMQP. I'm not sure how flexible this should be and whether it should take into account an actual message content. But the minimal useful implementation would be something that will allow us to set `content-type` and `content-encoding` properties on all messages published through MQTT.

**Comment by michaelklishin** [comment]
And why do we need this feature? This plugin already has a bunch of really opinionated features that virtually nobody uses. I'm 👎  on this.

**Comment by voron3x** [comment]
Becouse for some amqp clients like a kombu, we need define content type for decode payload. Right now it None.

**Comment by binarin** [comment]
E.g. celery depends on content-type/content-encoding fields. With this feature it'll be possible to mix MQTT and other publishers, and at the same time be able to use celery built-in decoding mechanisms (i.e. without any modifications to consumer).

But I also agree that this plugin is already a bit bloated with features that are unrepresentable in MQTT =(

**Comment by michaelklishin** [comment]
I honestly think that MQTT users should complain loudly to the MQTT spec authors so that they make the protocol at least a little bit extensible and not built for the fantasy world where optional authentication is acceptable, servers never need to report custom errors to clients, or where applications magically work in concert without passing around much metadata.

**Comment by kjnilsson** [comment]
Making assumptions about content-types is probably better done by the client library on a per-consumer basis.

**Comment by binarin** [comment]
Thanks, I've convinced my peers that they don't need this feature =)

**Comment by michaelklishin** [comment]
@binarin thank you!
