### ISSUE TITLE
"Key exists" error when reading MQTT data

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-mqtt#132]
Originally reported by @yckim1 in https://github.com/rabbitmq/rabbitmq-server/issues/1199#issuecomment-297831749:

"Key exists" error during service using Rabbitmq's MQTT Plugin
We were sending messages using MQTT and receiving them using MQTT and did not use message ID
The error log refers to the attached file.

 - rabbitmq version : rabbitmq_server-3.6.4
 - erlang version : otp_src_19.0
 - os information : Linux tb-101.vclinux.dev 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
![image](https://cloud.githubusercontent.com/assets/28076134/25464172/ccf7f010-2b35-11e7-92ed-00cd0dd646ba.png)

**Comment by michaelklishin** [comment]
Some useful findings by @lukebakken: https://github.com/rabbitmq/rabbitmq-server/issues/1199#issuecomment-297831749.

**Comment by lukebakken** [comment]
Your ["after a period of time"](https://github.com/rabbitmq/rabbitmq-server/issues/1199#issuecomment-297833939) comment gave me an idea. I wonder if the collision happens when the client sends enough messages to overflow (and thus reset) the 16-bit message id before the server has time to send enough replies to catch up. I'll modify the Go sample code and my environment to see if I can trigger it that way.

**Comment by michaelklishin** [comment]
That's over 65K messages pending processing, not unrealistic but also a non-trivial amount. Good find!

**Comment by lukebakken** [comment]
Well, it's just an idea at this point 😄 I'm going to run the server in a CPU and disk i/o constrained cgroup to try to reproduce heavy load. I'll let you know what I find.

**Comment by yckim1** [comment]
The mqtt client library used paho's mqtt-client-0.4.0.jar
QoS is 1.

**Comment by michaelklishin** [comment]
@yckim1 thanks. What would really help us is relevant snippets (or a pretty detailed description of) your code.

**Comment by lukebakken** [comment]
ML thread: https://groups.google.com/forum/#!topic/rabbitmq-users/TtlnsQ6tQnw

**Comment by lukebakken** [comment]
@yckim1 - in a mailing list message you made the following statement:

> It happened when I restarted mqtt client while receiving(subscribing) 3 messages per second.

Can you please provide more detail on what you mean by "restarted"? Did the previous process stop without making a clean shutdown?

**Comment by yckim1** [comment]
"Restarted" means that the previous Client process has been completely terminated and a new Client process has been started

**Comment by yckim1** [comment]
There is a Source ("Global.scala" and "MQTTSubscriber.scala") in "https://groups.google.com/forum/#!topic/rabbitmq-users/TtlnsQ6tQnw".

 

The development language of the source is scala, and playframework is used.

 

The source is only an excerpt from the MQTT subscribe (we can not give the whole because our source is running for the actual service).

**Comment by lukebakken** [comment]
@yckim1 - could you give more information about the impact of this error? Did you lose messages or experience other negative effects?

> It was first time error that we haven't seen for 6 months and it can not be reproduced again.

Can you confirm that you have not seen this error again since your original report?

Thanks -
Luke

**Comment by michaelklishin** [comment]
With QoS 1 any terminating channel should cause deliveries to be re-queued because [manual acknowledgements](https://www.rabbitmq.com/confirms.html) should be used internally by the plugin.

**Comment by yckim1** [comment]
Sorry for the delay.
After restarting the MQTT Client, some messages are received first, but the messages are not received immediately.
After the error occurred, Rabbitmq and Mqtt Client restarted and no error occurred.

**Comment by yckim1** [comment]
What is the problem with "key exists"?

**Comment by yckim1** [comment]
Sorry for the delay.
After restarting the MQTT Client, some messages are received first, but the messages are not received immediately.
After the error occurred, Rabbitmq and Mqtt Client restarted and no error occurred.

 

What is the problem with "key exists"?

**Comment by michaelklishin** [comment]
If we knew what the root cause we'd have explained it already. Lines have changed since 3.6.4 but it's likely [this line](https://github.com/rabbitmq/rabbitmq-mqtt/blob/stable/src/rabbit_mqtt_processor.erl#L357) where a message is put into a dictionary of pending acknowledgements and another message with the same ID already exists there.

**Comment by michaelklishin** [comment]
@yckim1 can you please post relevant sections of your code (not the client library)? That would really help as we cannot reproduce this otherwise.

**Comment by yckim1** [comment]
Thank you for answer.

 

rabbitmq의 버그인가요?

"Key exists"을 발생하지 않기 위해 우리는 어떻게 해야 합니까?

**Comment by yckim1** [comment]
Thank you for answer.

 

Is it a rabbitmq bug?

What should we do to avoid "Key exists"?

From: 김영채 [mailto:yckim@ntels.com] 
Sent: Thursday, May 18, 2017 10:01 AM
To: 'rabbitmq/rabbitmq-mqtt' <reply@reply.github.com>; 'rabbitmq/rabbitmq-mqtt' <rabbitmq-mqtt@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [rabbitmq/rabbitmq-mqtt] "Key exists" error when reading MQTT data (#132)

 

Thank you for answer.

 

rabbitmq의 버그인가요?

"Key exists"을 발생하지 않기 위해 우리는 어떻게 해야 합니까?

**Comment by michaelklishin** [comment]
@yckim1 we do not know what exactly the issue is, so I cannot say whether this is a bug or not and what options there are to avoid it. Therefore "we" should find a way to *reproduce* the issue first.

Please do provide a code example that demonstrates what you did to run into this exception, without it the only thing we can do is to close this issue.

**Comment by yckim1** [comment]
Hello Michael!
Thank you for your reply.

Because the entire code is so large and it contains a lot of business logic, we can provide a fraction of the total.
I am sorry about that.

The code language is ‘scala’, and ‘playframework’ is used.
[N-MAS-Device-Front-End.zip](https://github.com/rabbitmq/rabbitmq-mqtt/files/1009888/N-MAS-Device-Front-End.zip)

**Comment by michaelklishin** [comment]
@yckim1 we are obviously not asking for the entire codebase, only the parts that demonstrate what you do w.r.t. MQTT (so, primarily how you publish and consume).

**Comment by yckim1** [comment]
The consume code is "MQTTSubscriber.scala".

 

The publish code is " MQTTSubscriber.scala".

**Comment by lukebakken** [comment]
Older `rabbitmq-users` thread exhibiting same problem: https://groups.google.com/forum/#!starred/rabbitmq-users/frm5TShQW-0

**Comment by lukebakken** [comment]
I used the code from [here](https://groups.google.com/forum/#!starred/rabbitmq-users/frm5TShQW-0) and reproduced this issue by passing `-S 1:1` to the VM. Continuing to investigate.

**Comment by lukebakken** [comment]
Running rabbitmq in a restricted environment via this command also reproduces the issue:

```
systemd-run -p 'CPUWeight=50' -p 'CPUQuota=10%' --tty --uid=lbakken --gid=lbakken /bin/bash
```

**Comment by lukebakken** [comment]
[This code](https://github.com/rabbitmq/rabbitmq-mqtt/blob/master/src/rabbit_mqtt_reader.erl#L120-L123) is being called twice for the same `ProcState#proc_state.message_id` value.
