### ISSUE TITLE
Investigate if client ID can be safely propagated to authn backends

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-mqtt#139]
See https://github.com/rabbitmq/rabbitmq-mqtt/pull/137 for the idea. This makes sense for some authn backends (e.g. HTTP, possibly LDAP) but not others (e.g. internal database backend won't use the client ID value).

[rabbit_authn_backend: user_login_authentication/2](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_authn_backend.erl) already accepts additional options.

@acogoluegnes may have additional thoughts.

**Comment by acogoluegnes** [comment]
The authentication backends usually extract the credentials from a list of tuples (e.g. [in the internal backend](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_auth_backend_internal.erl#L104). So it should be safe to add an extra `client_id` tuple.

Unfortunately, the most obvious location to pass in the client ID would be in [`rabbit_direct`](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_direct.erl#L82) (so not just in the MQTT plugin), where the connection info is available (with the MQTT client ID inside it). We could change [this call](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_direct.erl#L74).

**Comment by michaelklishin** [comment]
@acogoluegnes what if we detect what protocol is used in `connect/5` and come up with a convention that retrieves additional arguments from a module in that plugin, e.g. `rabbit_mqtt_connection_info`, `rabbit_stomp_connection_info`, etc. This way `rabbit_direct` would have next to no protocol-specific bits. Connection info modules can return a proplist/map that is merged with the credentials we already pass on.

**Comment by acogoluegnes** [comment]
@michaelklishin Looks good to me, thanks. Stable or master?

**Comment by michaelklishin** [comment]
@acogoluegnes master only sounds reasonable to me.

**Comment by michaelklishin** [comment]
I should clarify the function in e.g. `rabbit_mqtt_connection_info`, say, `rabbit_mqtt_connection_info:additional_authn_params/N`, will accept some or all of the same arguments as `connect/5`. Providing more context sounds like the right thing to do here.

**Comment by rasgele** [comment]
Requests to my auth backend server's `auth/user` has this body:
` {username: "guest", password: "guest", vhost: "/"}`
Although in /auth/topic I receive such body, 
```
{ 
  username: 'guest',
  vhost: '/',
  resource: 'topic',
  name: 'amq.topic',
  permission: 'write',
  routing_key: 'mytenant.agent-00000000.inbox',
  'variable_map.client_id': 'publisherclient-randomid-0',
  'variable_map.username': 'guest',
  'variable_map.vhost': '/' 
}
```
So it seems extra props(e.g. client_id) is not passed for auth endpoint. Am I missing smth?

P.S. I run 3.7.6 version( `{rabbit,"RabbitMQ","3.7.6"}`)

**Comment by michaelklishin** [comment]
@rasgele `'variable_map.client_id': 'publisherclient-randomid-0'` does look like a client ID to me. Please use the mailing list for discussions.
