### ISSUE TITLE
MQTT connections don't adhere to connection log level settings

### ISSUE THREAD

**Issue by agallojr** [rabbitmq/rabbitmq-mqtt#142]
Rabbit docs suggest log levels can be throttled such as: 

```
{ log_levels, [ {channel, error}, {connection, error}, {federation, error}, {mirroring, error} ] }
```

But logging from the MQTT / Web-MQTT plugins doesn't seem to respect these settings.  

For example: 

```
=INFO REPORT==== 24-Jul-2017::19:45:48 ===
MQTT vhost picked using plugin configuration or default
```

In my high-volume use case, these logs are pilling up.  I'm forced to suppress all logging in the Docker container in which my Rabbit runs, else I blow up my disk space pretty quickly.  

It would be very useful to be able to throttle the plugin logging down to error level when desired.

Thanks.

**Comment by hairyhum** [comment]
The `rabbit_mqtt_reader` module, which represents MQTT connection, does log to `connection` log, but `rabbit_mqtt_processor`, which processes logical frames, logs to default log.
Should it log to `connection` level or `channel` level, because it's closer to channel in AMQP terms?
