### ISSUE TITLE
retain flag

### ISSUE THREAD

**Issue by financedemo** [rabbitmq/rabbitmq-mqtt#15]
Any ideas when retain flag will be implemented?

**Comment by michaelklishin** [comment]
We make no promises about dates. May be in the next release (3.5) if we have time. Please ask questions on rabbitmq-users and [search archives](https://groups.google.com/forum/#!searchin/rabbitmq-users/RETAIN/rabbitmq-users/RyhyId5o6kk/xmoemc5h71UJ) first. This repository is currently just a mirror.
