### ISSUE TITLE
Report client ID in connection metadata

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-mqtt#152]
See #151.

We had a couple of spikes around this a few years ago. This may be useful for monitoring. With additional connection metadata introduced and reported by management UI since then, it should be possible to do this without (or with fewer) temporary solutions we didn't like.

Therefore, there should be a way to:

 - [ ] Find MQTT client ID out in the management UI
 - [x] Report MQTT client ID using `rabbitmqctl` (already possible: see `rabbitmqctl list_mqtt_connections`)

**Comment by michaelklishin** [comment]
We may want to look into #91 before addressing this, however.

**Comment by haiyangu** [comment]
So will the mqtt client id be added to connection properties in the coming version?

**Comment by haiyangu** [comment]
So can we get the mqtt client id in the currect rabbitmq vesion? Either from GUI, cmds or log?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There is a column, "additional client info", in connection details but it just says "MQTT client" for MQTT clients. That's a natural way to display the ID in.

`rabbitmqctl list_mqtt_connections` has a `client_id` column reported by default.

**Comment by michaelklishin** [comment]
As of `3.7.11` the client ID is displayed in the connection table as a subscript in the Client [info] column. It is truncated to 120 characters in the UI.

It's been displayed in Client properties on the connection page for a while, and `rabbitmqctl list_mqtt_connections` is available as of RabbitMQ 3.7.0 (note: the management plugin must be enabled for it to be discoverable by/available to CLI tools).
