### ISSUE TITLE
Topic rewrite when bridging

### ISSUE THREAD

**Issue by BB8-fenix** [rabbitmq/rabbitmq-mqtt#158]
On publish/subscribe, there is no mechanism for rewriting the topic at broker end.

For example, 

- if broker receives a message on topic "topic/urgent/data" from a bridge and it should be subscribed on "topic/very/urgent/data"

- if a client publishes on topic "topic/urgent/data" and it should be subscribed on "topic/very/urgent/data"

there is no mechanism to achieve this kind of situation.

**Comment by michaelklishin** [comment]
I don't think we are interested in having one before #58 is addressed, which is some time away.
