### ISSUE TITLE
session present flag always set to true

### ISSUE THREAD

**Issue by amalikctec** [rabbitmq/rabbitmq-mqtt#163]
Hi

RabbitMQ Version: 3.7.7
RabbitMQ-MQTT Version: 3.7.7

I have come across a bug in the MQTT plugin regarding the 'session present' flag. It seems it is not working correctly in all scenarios. If i understand correctly the session present flag's value depends on the following:

1. If 'clean session' is set to true then 'session present' is set to false. (this is working as expected).
2. If 'clean session' is set to false then the value 'session present' depends on whether a session (queue in this case) is present or not.

It seems in the second scenario the 'session present' flag is always true regardless of whether a session (queue) for that clientId is present or not.

This can be seen in the following (node.js) sample that always connects with a new client ID. The host can be switched between 'test.mosquitto.org' and localhost (tested with the latest RabbitMQ docker image).
https://we.tl/CBYBXixjCc

It seems there is code that checks if the queue is declared (using the passive bit) in rabbit_mq_processor. Also checked if its an issue in the rabbitmq AMQP plugin, but that seems to be working properly (again tested using the node.js amqp client). Following is the code snippet i am referring to:

session_present(Channel, ClientId)  ->
    {_, QueueQ1} = rabbit_mqtt_util:subcription_queue_name(ClientId),
    Declare = #'queue.declare'{queue   = QueueQ1,
                               passive = true},
    case amqp_channel:call(Channel, Declare) of
        #'queue.declare_ok'{} -> true;
        _                     -> false
    end.

Please let me know if you require more information.

Thanks

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by amalikctec** [comment]
Bump.
Is this plug-in abandoned? We are looking into using rabbitMQ as an MQTT broker and the above is a critical issues as that caused data loss (the device does not sync). There it is a blocker.

Thanks

**Comment by michaelklishin** [comment]
Let's assume that there's enough evidence to reproduce and try to fit it into 3.7.8.

**Comment by amalikctec** [comment]
Great to hear that this plug-in is not abandoned. Please let me know if you guys need anything from our end.
We would like to contribute however we dont currently have in-house erlang expertise. Once in production with this we would like to take more ownership and contribute. In the meanwhile it would be great if you guys can provide a fix.

Thanks

**Comment by michaelklishin** [comment]
@amalikctec can you please attach your code sample to this issue as a .zip or tarball? Apparently the WeTransfer link is defunct.

**Comment by amalikctec** [comment]
[rabbitmq-session-present-mqtt-test.zip](https://github.com/rabbitmq/rabbitmq-mqtt/files/2305106/rabbitmq-session-present-mqtt-test.zip)

**Comment by amalikctec** [comment]
Please see attached. You can check the discrepancy by switching the HOST between a RabbitMQ deployment (i am using the official docker image) and the public Mosquitto broker. The response on the connect event is printed out to the console.

**Comment by dcorbacho** [comment]
Thanks for the code sample @amalikctec!

**Comment by amalikctec** [comment]
Thanks for the fix!
