### ISSUE TITLE
Provide protocol-specific context (e.g. client ID) to authN and authZ backends

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-mqtt#168]
It would be beneficial to expose protocol-specific information (namely client ID in this case) to [authN and authZ backend interfaces](http://www.rabbitmq.com/access-control.html). This will require changes
in the core.

Originally filed as https://github.com/rabbitmq/rabbitmq-auth-backend-http/issues/78.

**Comment by acogoluegnes** [comment]
The original issue mentioned the client id for topic authorization, which has a context parameter (key-value pairs). So this specific feature could go in to 3.7 without breaking the authorization API, this is worth investigating.

**Comment by acogoluegnes** [comment]
OK, [`client_id` is propagated for topic authorization](https://github.com/rabbitmq/rabbitmq-mqtt/blob/d92fa2aed107147e4bab1ae8cc0dc5dddfcc4b75/src/rabbit_mqtt_processor.erl#L855-L863), so we can use the same design to extend it to other authn and authz functions (it's a breaking change).

**Comment by michaelklishin** [comment]
@acogoluegnes OK. It's a breaking change in an internal interface so we potentially can backport it to 3.7.x anyway since all but one popular implementations are maintained by our team.

**Comment by acogoluegnes** [comment]
Implemented as part of https://github.com/rabbitmq/rabbitmq-server/issues/1767.
