### ISSUE TITLE
Topic_auth called twice during mqtt subscribe request, could it be reduced

### ISSUE THREAD

**Issue by Dongsheng-LI** [rabbitmq/rabbitmq-mqtt#181]
RabbitMQ version : 3.7.10
RabbitMQ MQTT Plugin version: 3.7.10

http packet as follows
POST /mqtt-adapter/v1/auth/topic HTTP/1.1
content-type: application/x-www-form-urlencoded
content-length: 252
connection: keep-alive

username=foo&vhost=%2F&resource=topic&name=amq.topic&permission=read&routing_key=ce6f2776-1aec-4fd5-9645-607ea5538fc6&variable_map.client_id=828fba085d9649b29bbd168215f8afd5&variable_map.username=foo&variable_map.vhost=%2FHTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 5

allow

POST /mqtt-adapter/v1/auth/resource HTTP/1.1
content-type: application/x-www-form-urlencoded
content-length: 133
connection: keep-alive

username=foo&vhost=%2F&resource=queue&name=mqtt-subscription-828fba085d9649b29bbd168215f8afd5qos0&permission=configureHTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 5

allow

POST /mqtt-adapter/v1/auth/resource HTTP/1.1
content-type: application/x-www-form-urlencoded
content-length: 128
connection: keep-alive

username=foo&vhost=%2F&resource=queue&name=mqtt-subscription-828fba085d9649b29bbd168215f8afd5qos0&permission=readHTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 5

allow

POST /mqtt-adapter/v1/auth/resource HTTP/1.1
content-type: application/x-www-form-urlencoded
content-length: 129
connection: keep-alive

username=foo&vhost=%2F&resource=queue&name=mqtt-subscription-828fba085d9649b29bbd168215f8afd5qos0&permission=writeHTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 5

allow

POST /mqtt-adapter/v1/auth/resource HTTP/1.1
content-type: application/x-www-form-urlencoded
content-length: 86
connection: keep-alive

username=foo&vhost=%2F&resource=exchange&name=amq.topic&permission=readHTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 5

allow

POST /mqtt-adapter/v1/auth/topic HTTP/1.1
content-type: application/x-www-form-urlencoded
content-length: 252
connection: keep-alive

username=foo&vhost=%2F&resource=topic&name=amq.topic&permission=read&routing_key=ce6f2776-1aec-4fd5-9645-607ea5538fc6&variable_map.client_id=828fba085d9649b29bbd168215f8afd5&variable_map.username=foo&variable_map.vhost=%2FHTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 5

allow

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
We cannot suggest much since you haven't provided any MQTT client code to use. Virtually every `rabbitmq_auth_backend_http` user eventually adopts [rabbitmq_auth_backend_cache](https://github.com/rabbitmq/rabbitmq-auth-backend-cache/) which completely hides any additional calls.

I remember @lukebakken investigated something similar before but can't find any details.

**Comment by lukebakken** [comment]
@Dongsheng-LI - use the cache backend as well. This "double auth" is part of how the MQTT plugin uses AMQP.
