### ISSUE TITLE
Authentication with SSL client certificates fails

### ISSUE THREAD

**Issue by mlasak** [rabbitmq/rabbitmq-mqtt#19]
Struggling for some days to get rabbitmq-mqtt working with client certificate authentication i hope to find a solution by contributing a test for easy reproduction of the issue. The minimal test is to check the "Authentication with SSL client certificates" feature as described at https://www.rabbitmq.com/mqtt.html and in principle adds only an alternative server test configuration while reusing the existing ```MqttSSLTest``` test to conform the docs. If something is missing i am more than happy for your pointers...

https://github.com/mlasak/rabbitmq-mqtt/commit/9c7d04abdfbb8c71e01bbc64f9363797716b0436
(I will raise a pull request for this test but would be glad to change if anything does not conform contribution guidelines)

As you see the changes are kept to a minimum, just needed/documented bits that are required to get the feature running after studying through the docs. 

How to run the test and reproduce the issue (assuming use of the above rabbitmq-mqtt changes):
```
$ cd rabbitmq-mqtt
$ unset RABBITMQ_MQTT_SSLTEST_ONLY
$ make test
# --> Tests are successful. Now switch on client certificate authentication
$ export RABBITMQ_MQTT_SSLTEST_ONLY=1
$ make test
# --> Tests fail with the following error log (Full log here: https://gist.github.com/mlasak/4a8ee598fc340f60ab23)
```

Error log:

```
=INFO REPORT==== 21-Apr-2015::12:26:43 ===
accepting MQTT connection <0.444.0> (XXX.XXX.XXX.XXX:57676 -> XXX.XXX.XXX.XXX:8883)

=ERROR REPORT==== 21-Apr-2015::12:26:43 ===
SSL: certify: ssl_connection.erl:398:Fatal error: handshake failure

=ERROR REPORT==== 21-Apr-2015::12:26:48 ===
MQTT detected TLS upgrade error on XXX.XXX.XXX.XXX:57674 -> XXX.XXX.XXX.XXX:8883: handshake failure

=ERROR REPORT==== 21-Apr-2015::12:26:48 ===
** Generic server <0.436.0> terminating
** Last message in was {'$gen_cast',
                           {go,#Port<0.6181>,
                               #Fun<rabbit_networking.3.38010331>,<0.437.0>}}
** When Server state == undefined
** Reason for termination == 
** {network_error,{ssl_upgrade_error,{tls_alert,"handshake failure"}},
                  "XXX.XXX.XXX.XXX:57674 -> XXX.XXX.XXX.XXX:8883"}
```

I've tested on OSX 10.10.3 with following versions:
- rabbitmq 3.5.0 and 3.5.1, each from github using umbrella AND from the release archive
- Erlang/OTP 17 
- OpenSSL 0.9.8zd 8 Jan 2015

Thank you for your attention and any help.

**Comment by michaelklishin** [comment]
What's in the SASL log?

**Comment by mlasak** [comment]
That is the SASL log: https://gist.github.com/mlasak/8d9f9142da768fd457e0

**Comment by michaelklishin** [comment]
Both logs reveal `ssl_upgrade_error`. We possibly could avoid the error report but all it means that a connection cannot proceed.

Have you tried using [tls-gen](https://github.com/michaelklishin/tls-gen) certificates to compare? I'm not convinced this is a bug. It easily can be a certificate issue.

**Comment by michaelklishin** [comment]
Start with making sure that TLS connections with user credentials succeed: [Troubleshooting TLS](http://www.rabbitmq.com/troubleshooting-ssl.html).

Then switch to certificate-only authentication.

**Comment by mlasak** [comment]
Thanks for the hints. Of course i went through the Troubleshooting TLS page and succeeded to connect via openssl but had less success using stunnel. I'll give it a try again here.

But just to double check: You don't get any connection errors if using the tests on your current master PLUS having the https://github.com/rabbitmq/rabbitmq-mqtt/blob/master/test/src/test.config modified to ```{fail_if_no_peer_cert,true}```

**Comment by michaelklishin** [comment]
If OpenSSL's `s_client` works and you can connect with TLS using "regular" credentials, it means your configuration is sane, so don't worry about `stunnel`.

**Comment by michaelklishin** [comment]
@mlasak as you can see some MQTT TLS tests do not use client certificates. So they *will* fail with `{fail_if_no_peer_cert,true}`.

**Comment by michaelklishin** [comment]
Let me know if/when there are updates on this.

**Comment by mlasak** [comment]
@michaelklishin Thanks to the existing functional tests (https://github.com/rabbitmq/rabbitmq-mqtt/blob/f828199dceb4e83035d3c8eee6b44007f3467ae0/test/src/com/rabbitmq/mqtt/test/tls/MqttSSLTest.java#L115) i was able to get mutual certificate based authentication working. I think this issue should be closed as "not a bug". But maybe someone stumbles over same problems and finds this useful. Cheers.

**Comment by michaelklishin** [comment]
Thank you for getting back to clarify!
