### ISSUE TITLE
Old subscriptions not stored on sticky session

### ISSUE THREAD

**Issue by vinpuli** [rabbitmq/rabbitmq-mqtt#2]
When the mqtt client disconnects and reconnects and clean session is false then all the old subscriptions need to be restored. But here none of the old subscriptions are present. Client needs to subscribe again for the channels

**Comment by michaelklishin** [comment]
We're preparing to switch to GitHub issues after the 3.5.0 release. I'm closing this as fairly old. If this is still relevant after `3.5.0`, please open a new issue. Thank you.
