### ISSUE TITLE
3.8: client ID tracker [Raft] cluster unavailability should not prevent plugin from starting

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-mqtt#200]
Currently it will.

@kjnilsson suggested that we periodically try to rejoin Raft cluster peers as they may become available at a later point. A tracker node that cannot reach its Raft cluster peers won't be able to accept connections in the meantime (the availability price you pay for Raft's consistency and recovery predictability).

**Comment by acogoluegnes** [comment]
To reproduce: set up a 3-node cluster with MQTT plugin enabled, stop all the nodes, then start only one. The MQTT plugin should fail during startup.
