### ISSUE TITLE
How do I modify the default switch {exchange, <<"amq.topic">> in the MQTT plug-in

### ISSUE THREAD

**Issue by yueyou16** [rabbitmq/rabbitmq-mqtt#212]
How do I modify the default switch {exchange, <<"amq.topic">> in the MQTT plug-in .{rabbitmq_mqtt, [{default_user,     <<"mqtt-test">>},
                  {default_pass,     <<"mqtt-test">>},
                  {allow_anonymous,  true},
                  {vhost,            <<"/">>},
                  {exchange,         <<"amq.topic">>},

**Comment by yueyou16** [comment]
> 也许看到这个[配置示例](https://www.rabbitmq.com/mqtt.html#config)。

thank you

**Comment by yueyou16** [comment]
> 也许看到这个[配置示例](https://www.rabbitmq.com/mqtt.html#config)。

thank you

**Comment by ailusa** [comment]
@yueyou16  I meet the same question, how do you fixed it?

**Comment by michaelklishin** [comment]
See `mqtt.exchange` in [MQTT Plugin Configuration](https://www.rabbitmq.com/mqtt.html#config).
