### ISSUE TITLE
Client ID tracker should try to query all available nodes

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-mqtt#213]
Instead of just one (the local one), as the node itself can be disconnected or removed from the cluster.

Filing retroactively, addressed by @dumbbell and @kjnilsson in https://github.com/rabbitmq/rabbitmq-mqtt/commit/95fd15409ace7523b7153c6a340a0b910354d414.

**Comment by lichenglin** [comment]
hello ,do you mean the MQTT Plugin. what's the result of this issue?
I have met the same situation.
I have a rabbitmq cluster, and when one node down, all the client disconnect and can't reconnect.

**Comment by michaelklishin** [comment]
@lichenglin we cannot comment as we don't even know how many nodes there are total. In 3.8, MQTT plugin requires a majority of nodes to be online in order to be able to accept connections. This means 2 nodes out of 3, 3 out of 5 and so on. There is no quorum with one or two nodes.

Please direct your questions to the RabbitMQ mailing list.

**Comment by lichenglin** [comment]
> @lichenglin we cannot comment as we don't even know how many nodes there are total. In 3.8, MQTT plugin requires a majority of nodes to be online in order to be able to accept connections. This means 2 nodes out of 3, 3 out of 5 and so on. There is no quorum with one or two nodes.
> 
> Please direct your questions to the RabbitMQ mailing list.

sorry but I have tested on 3.8.2 with 3 node.

It still lost connection  when only one node shutdown, and can't reconnect.

by the way,I use "org.eclipse.paho.client.mqttv3" as the client.
