### ISSUE TITLE
MQTT "due to an internal error or unavailable component"

### ISSUE THREAD

**Issue by ttxzheng2019** [rabbitmq/rabbitmq-mqtt#221]
The cluster has 6 nodes, if 1 or 2 nodes are down，MQTT could be connected. When 3 nodes or more than 3 nodes are down, MQTT couldn't be connected. But if we use AMQP connection method,  the AMQP could be connected even there was only one node survived. We think that MQTT could also be connected if there is anynode alive. The server side error is as bellow:

2019-11-12 15:36:33.698 [error] <0.15599.2> MQTT cannot accept a connection: client ID registration timed out
2019-11-12 15:36:33.698 [error] <0.15599.2> MQTT cannot accept connection x.x.x.x:50528 -> x.x.x.x:1883 due to an internal error or unavailable component

* RabbitMQ version:3.8.0
* Erlang version:Erlang 22.1.4

I want to know the reason why MQTT couldn't be connected when more than 3 nodes are down. Looking forward for your suggection. Thank you very much.

**Comment by michaelklishin** [comment]
MQTT plugin in 3.8 uses Raft for client ID tracking. Raft requires the majority of nodes to be online in order to make progress. This is the price you pay for consistent cluster-wide client ID tracking.
