### ISSUE TITLE
unsuscribe not respond if was prewios DUB message.

### ISSUE THREAD

**Issue by DariusBabrauskas** [rabbitmq/rabbitmq-mqtt#229]
Issue occurs, when "poor wifi or gsm connection" and mqtt client begun repeat messages with DUP  flag.
If then client send unsubscribe message, server not respond to this and respond only  old  respond to DUB message. Client waiting about 10 seconds, then timeout occurs. Client log below.

Server: RabbitMQ logo 3.7.24 Erlang 22.3
Client: Aws FreeRtos MQTT
Qs1

rabbitmq-plugins list
Listing plugins with pattern ".*" ...
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: * = running on **************
 |/
[  ] rabbitmq_amqp1_0                  3.7.24
[  ] rabbitmq_auth_backend_cache       3.7.24
[  ] rabbitmq_auth_backend_http        3.7.24
[  ] rabbitmq_auth_backend_ldap        3.7.24
[  ] rabbitmq_auth_mechanism_ssl       3.7.24
[  ] rabbitmq_consistent_hash_exchange 3.7.24
[  ] rabbitmq_event_exchange           3.7.24
[  ] rabbitmq_federation               3.7.24
[  ] rabbitmq_federation_management    3.7.24
[  ] rabbitmq_jms_topic_exchange       3.7.24
[E*] rabbitmq_management               3.7.24
[e*] rabbitmq_management_agent         3.7.24
[E*] rabbitmq_mqtt                     3.7.24
[  ] rabbitmq_peer_discovery_aws       3.7.24
[  ] rabbitmq_peer_discovery_common    3.7.24
[  ] rabbitmq_peer_discovery_consul    3.7.24
[  ] rabbitmq_peer_discovery_etcd      3.7.24
[  ] rabbitmq_peer_discovery_k8s       3.7.24
[  ] rabbitmq_random_exchange          3.7.24
[  ] rabbitmq_recent_history_exchange  3.7.24
[  ] rabbitmq_sharding                 3.7.24
[  ] rabbitmq_shovel                   3.7.24
[  ] rabbitmq_shovel_management        3.7.24
[  ] rabbitmq_stomp                    3.7.24
[  ] rabbitmq_top                      3.7.24
[  ] rabbitmq_tracing                  3.7.24
[  ] rabbitmq_trust_store              3.7.24
[e*] rabbitmq_web_dispatch             3.7.24
[  ] rabbitmq_web_mqtt                 3.7.24
[  ] rabbitmq_web_mqtt_examples        3.7.24
[  ] rabbitmq_web_stomp                3.7.24
[  ] rabbitmq_web_stomp_examples       3.7.24

Client log:

UnsubscribeSync->mqttexampleclient/example/topic t:2216521
[DEBUG][THREAD][lu] Locking mutex 0xc0c32b38.
[DEBUG][THREAD][lu] Unlocking mutex 0xc0c32b38.
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0) Creating new operation record.
[DEBUG][THREAD][lu] Locking mutex 0xc0c32ac8.
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0) Reference count changed from 2 to 3.
[DEBUG][THREAD][lu] Unlocking mutex 0xc0c32ac8.
[DEBUG][THREAD][lu] Creating new semaphore 0xc0c32c88.
[DEBUG][THREAD][lu] Locking mutex 0xc0c32ac8.
[DEBUG][THREAD][lu] Unlocking mutex 0xc0c32ac8.
[DEBUG][MQTT][lu] MQTT UNSUBSCRIBE packet:
a2 23 08 95 00 1f 6d 71 74 74 65 78 61 6d 70 6c 
65 63 6c 69 65 6e 74 2f 65 78 61 6d 70 6c 65 2f 
74 6f 70 69 63 
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0, UNSUBSCRIBE operation 0xc0c32c40) Sending MQTT packet.
c>m:AT+QSSLSEND=3,37
c<md:>
c<md: 
c<md:SEND OK
[DEBUG][THREAD][lu] Locking mutex 0xc0c32ac8.
[DEBUG][THREAD][lu] Locking mutex 0xc0c32ac8.
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0, UNSUBSCRIBE operation 0xc0c32c40) Job reference changed from 2 to 1.
[DEBUG][THREAD][lu] Unlocking mutex 0xc0c32ac8.
[DEBUG][THREAD][lu] Unlocking mutex 0xc0c32ac8.
[INFO ][MQTT][lu] (MQTT connection 0xc0c32ab0) UNSUBSCRIBE operation scheduled.
[DEBUG][THREAD][lu] Locking mutex 0xc0c32ac8.
[INFO ][MQTT][lu] (MQTT connection 0xc0c32ab0, UNSUBSCRIBE operation 0xc0c32c40) Waiting for operation completion.
[DEBUG][THREAD][lu] Unlocking mutex 0xc0c32ac8.
+QSSLURC: "recv",3,4
sock:0
receiveCallback
rxw:1 n:pool1
40 
rxw:1 n:pool1
02 
rxw:2 n:pool1
08 93 
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0) PUBACK in data stream.
Packet identifier 2195.
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0) Searching for operation PUBLISH pending response with packet identifier 2195.
[DEBUG][THREAD][lu] Locking mutex 0xc0c32ac8.
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0) Operation PUBLISH not found.
[DEBUG][THREAD][lu] Unlocking mutex 0xc0c32ac8.

......................
.....................
.......................

[WARN ][THREAD][lu] Timeout waiting on semaphore 0xc0c32c88.
[INFO ][MQTT][lu] (MQTT connection 0xc0c32ab0, UNSUBSCRIBE operation 0xc0c32c40) Wait complete with result TIMEOUT.
[DEBUG][THREAD][lu] Locking mutex 0xc0c32ac8.
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0, UNSUBSCRIBE operation 0xc0c32c40) Job reference changed from 1 to 0.
[DEBUG][THREAD][lu] Unlocking mutex 0xc0c32ac8.
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0, UNSUBSCRIBE operation 0xc0c32c40) Destroying operation.
[DEBUG][THREAD][lu] Locking mutex 0xc0c32ac8.
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0, UNSUBSCRIBE operation 0xc0c32c40) Removed operation from connection lists.
[DEBUG][THREAD][lu] Unlocking mutex 0xc0c32ac8.
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0, UNSUBSCRIBE operation 0xc0c32c40) MQTT packet freed.
[DEBUG][THREAD][lu] Destroying semaphore 0xc0c32c88.
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0, UNSUBSCRIBE operation 0xc0c32c40) Wait semaphore destroyed.
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0, UNSUBSCRIBE operation 0xc0c32c40) Operation record destroyed.
[DEBUG][THREAD][lu] Locking mutex 0xc0c32ac8.
[DEBUG][MQTT][lu] (MQTT connection 0xc0c32ab0) Reference count changed from 3 to 2.
[DEBUG][THREAD][lu] Unlocking mutex 0xc0c32ac8.
UnsubscribeSync res:TIMEOUT t:2226635

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I'm afraid we cannot conclude what may be happening. We need server logs from all nodes, an executable way to reproduce and ideally a traffic capture.
