### ISSUE TITLE
Can you add an unconditional authentication option?

### ISSUE THREAD

**Issue by zerothree3782** [rabbitmq/rabbitmq-mqtt#230]
Hello. 
First of all, I apologize for my poor English.
I am using RabbitMQ 3.8.3 version and eralng 22.2.4 version.
There is one issue in use.
The anonymous option now works only when the username and password are not entered.
I need the option to unconditionally authenticate without checking the ID and password.
I think you can do it like an anonymous option by adding an unconditionally authentication option In the code below.

rabbitmq-mqtt/src/rabbit_mqtt_processor.erl 704 ~ 734 line.

``` erlang
creds(User, Pass, SSLLoginName) ->
    DefaultUser   = rabbit_mqtt_util:env(default_user),
    DefaultPass   = rabbit_mqtt_util:env(default_pass),
    {ok, Anon}    = application:get_env(?APP, allow_anonymous),
    {ok, TLSAuth} = application:get_env(?APP, ssl_cert_login),
    HaveDefaultCreds = Anon =:= true andalso
                       is_binary(DefaultUser) andalso
                       is_binary(DefaultPass),

    CredentialsProvided = User =/= undefined orelse
                          Pass =/= undefined,

    CorrectCredentials = is_list(User) andalso
                         is_list(Pass),

    SSLLoginProvided = TLSAuth =:= true andalso
                       SSLLoginName =/= none,

    case {CredentialsProvided, CorrectCredentials, SSLLoginProvided, HaveDefaultCreds} of
        %% Username and password take priority
        {true, true, _, _}          -> {list_to_binary(User),
                                        list_to_binary(Pass)};
        %% Either username or password is provided
        {true, false, _, _}         -> {invalid_creds, {User, Pass}};
        %% rabbitmq_mqtt.ssl_cert_login is true. SSL user name provided.
        %% Authenticating using username only.
        {false, false, true, _}     -> {SSLLoginName, none};
        %% Anonymous connection uses default credentials
        {false, false, false, true} -> {DefaultUser, DefaultPass};
        %% Add unconditionally authentication option
        {true, false, false, true, unconditionally authentication = true} -> {DefaultUser, DefaultPass};
        _                           -> nocreds
    end.
```

I would appreciate it if you consider it.
Thank you.

**Comment by michaelklishin** [comment]
Anonymous "authentication" is an awful idea. Most messaging protocols do not provide it. Making it unconditional sounds like something we don't want. In addition, RabbitMQ core does not assume that authentication can be optional, hence a pair of default credentials that are always present in plugin's configuration (even if you don't configure them explicitly).

Sorry, we are not interested.

**Comment by zerothree3782** [comment]
Thank you for answer.
I think there was a misunderstanding.
I'm migrating from Mosquitto to RabbitMQ.
To explain in detail,
I'm using the RabbitMQ MQTT plugin mqtt.allow_anonymous configuration option. However, there is a problem my devices send a message with the ID and PW that I don't know. unfortunately It is not a situation where I can set up my devices. 
In Mosquitto, there is the option of not checking the ID and password. so i didn't know there would be a problem like that. 
in anonymous mode, is it possible to add an option to allow access to the default account like the existing anonymous mode when the ID and password are not authenticated?

**Comment by michaelklishin** [comment]
Optional authentication is a questionable idea but allowing arbitrary credentials (ignoring them entirely) is even worse. We are not interested in having such a feature, even if other projects decided to go with it.

However, RabbitMQ supports authentication via [LDAP](http://github.com/rabbitmq/rabbitmq-auth-backend-ldap/), [any HTTP service](https://github.com/rabbitmq/rabbitmq-auth-backend-http/). Obviously your own HTTP service or LDAP installation could effectively ignore credentials and unconditionally allow all operations. Then it would be your questionable security decision that only affects your products and not other RabbitMQ users.

It is possible to build a tiny plugin that would unconditionally authenticate and authorize all requests and use. Those backends work the same way for MQTT or any other supported protocol.
Again, this would be something that you build, choose to deploy and will be held accountable for when it all goes wrong.
