### ISSUE TITLE
RabbitMQ server crashes with docker container getting restarted with Error in MQTT plugin

### ISSUE THREAD

**Issue by dilpreetjuneja91** [rabbitmq/rabbitmq-mqtt#232]
Hi, I am new to Rabbit MQ and MQTT. I have deployed a container in my docker swarm. It keeps crashing in every 3-4 days. I got some logs. I am not quite understanding it clearly. If anyone can help me, that'd be great

Logs : 
{"log":"\n","stream":"stdout","time":"2020-06-11T13:22:55.430214635Z"}
=ERROR REPORT==== 11-Jun-2020::13:22:55 ===\n","stream":"stdout","time":"2020-06-11T13:22:55.430246025Z"}
{"log":"** Generic server \u003c0.16162.814\u003e terminating\n","stream":"stdout","time":"2020-06-11T13:22:55.430251541Z"}
{"log":"** Last message in was {inet_async,#Port\u003c0.5239149\u003e,32817,\n","stream":"stdout","time":"2020-06-11T13:22:55.430254777Z"}
{"log":"                           {ok,\u003c\u003c\"GET / HTTP/1.1\\r\\nHost: 45.77.154.206:1883\\r\\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0\\r\\n$
{"log":"** When Server state == {state,#Port\u003c0.5239149\u003e,\n","stream":"stdout","time":"2020-06-11T13:22:55.430261776Z"}
{"log":"                            \"10.255.0.4:8929 -\u003e 10.255.0.106:1883\",true,\n","stream":"stdout","time":"2020-06-11T13:22:55.430264668Z"}
{"log":"                            running,\n","stream":"stdout","time":"2020-06-11T13:22:55.430267672Z"}
{"log":"                            {none,none},\n","stream":"stdout","time":"2020-06-11T13:22:55.430270378Z"}
{"log":"                            \u003c0.16105.814\u003e,false,none,\n","stream":"stdout","time":"2020-06-11T13:22:55.4302741Z"}
{"log":"                            {proc_state,#Port\u003c0.5239149\u003e,\n","stream":"stdout","time":"2020-06-11T13:22:55.430278833Z"}
{"log":"                                {dict,0,16,16,8,80,48,\n","stream":"stdout","time":"2020-06-11T13:22:55.430283552Z"}
{"log":"                                    {[],[],[],[],[],[],[],[],[],[],[],[],[],\n","stream":"stdout","time":"2020-06-11T13:22:55.430287969Z"}
{"log":"                                     [],[],[]},\n","stream":"stdout","time":"2020-06-11T13:22:55.430292497Z"}
{"log":"                                    {{[],[],[],[],[],[],[],[],[],[],[],[],[],\n","stream":"stdout","time":"2020-06-11T13:22:55.430297406Z"}
{"log":"                                      [],[],[]}}},\n","stream":"stdout","time":"2020-06-11T13:22:55.430324721Z"}
{"log":"                                {undefined,undefined},\n","stream":"stdout","time":"2020-06-11T13:22:55.430329909Z"}
{"log":"                                {0,nil},\n","stream":"stdout","time":"2020-06-11T13:22:55.430348727Z"}
{"log":"                                {0,nil},\n","stream":"stdout","time":"2020-06-11T13:22:55.430351656Z"}
{"log":"                                undefined,1,undefined,undefined,undefined,\n","stream":"stdout","time":"2020-06-11T13:22:55.43035446Z"}
{"log":"                                {undefined,undefined},\n","stream":"stdout","time":"2020-06-11T13:22:55.43035782Z"}
{"log":"                                undefined,\u003c\u003c\"amq.topic\"\u003e\u003e,none}}\n","stream":"stdout","time":"2020-06-11T13:22:55.430360853Z"}
{"log":"** Reason for termination == \n","stream":"stdout","time":"2020-06-11T13:22:55.430364021Z"}
{"log":"** {{badmatch,\u003c\u003c\"T / HTTP/1.1\\r\\nHost: 45.77.154.206:1883\\r\\nUser-Agent: Mozilla/5.0 (Maci\"\u003e\u003e},\n","stream":"stdout","time":"2020-06-11T13:22:55.430366842Z"}
{"log":"    [{rabbit_mqtt_frame,parse_frame,3,[]},\n","stream":"stdout","time":"2020-06-11T13:22:55.43037026Z"}
{"log":"     {rabbit_mqtt_reader,process_received_bytes,2,[]},\n","stream":"stdout","time":"2020-06-11T13:22:55.430373137Z"}
{"log":"     {gen_server2,handle_msg,2,[]},\n","stream":"stdout","time":"2020-06-11T13:22:55.430375919Z"}
{"log":"     {proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]}\n","stream":"stdout","time":"2020-06-11T13:22:55.43037878Z"}
{"log":"\n","stream":"stdout","time":"2020-06-11T13:22:55.431258038Z"}
{"log":"=CRASH REPORT==== 11-Jun-2020::13:22:55 ===\n","stream":"stdout","time":"2020-06-11T13:22:55.431269106Z"}
{"log":"  crasher:\n","stream":"stdout","time":"2020-06-11T13:22:55.431272484Z"}
{"log":"    initial call: gen:init_it/6\n","stream":"stdout","time":"2020-06-11T13:22:55.43128154Z"}
{"log":"    pid: \u003c0.16162.814\u003e\n","stream":"stdout","time":"2020-06-11T13:22:55.431284758Z"}
{"log":"    registered_name: []\n","stream":"stdout","time":"2020-06-11T13:22:55.431303688Z"}
{"log":"    exception exit: {{badmatch,\u003c\u003c\"T / HTTP/1.1\\r\\nHost: 45.77.154.206:1883\\r\\nUser-Agent: Mozilla/5.0 (Maci\"\u003e\u003e},\n","stream":"stdout","time":"2020-06-11T13:22:55.4313359$
{"log":"                     [{rabbit_mqtt_frame,parse_frame,3,[]},\n","stream":"stdout","time":"2020-06-11T13:22:55.431342748Z"}
{"log":"                      {rabbit_mqtt_reader,process_received_bytes,2,[]},\n","stream":"stdout","time":"2020-06-11T13:22:55.43134561Z"}
{"log":"                      {gen_server2,handle_msg,2,[]},\n","stream":"stdout","time":"2020-06-11T13:22:55.43134835Z"}
{"log":"                      {proc_lib,init_p_do_apply,3,\n","stream":"stdout","time":"2020-06-11T13:22:55.431350975Z"}
{"log":"                                [{file,\"proc_lib.erl\"},{line,237}]}]}\n","stream":"stdout","time":"2020-06-11T13:22:55.431353669Z"}
{"log":"      in function  gen_server2:terminate/3 \n","stream":"stdout","time":"2020-06-11T13:22:55.431356423Z"}
{"log":"    ancestors: [\u003c0.16215.814\u003e,rabbit_mqtt_client_sup,rabbit_mqtt_sup,\n","stream":"stdout","time":"2020-06-11T13:22:55.431359455Z"}
{"log":"                  \u003c0.418.0\u003e]\n","stream":"stdout","time":"2020-06-11T13:22:55.431362252Z"}
{"log":"    messages: []\n","stream":"stdout","time":"2020-06-11T13:22:55.43136508Z"}
{"log":"    links: [\u003c0.16215.814\u003e,#Port\u003c0.5239149\u003e]\n","stream":"stdout","time":"2020-06-11T13:22:55.431367613Z"}
{"log":"    dictionary: []\n","stream":"stdout","time":"2020-06-11T13:22:55.43137051Z"}
{"log":"    trap_exit: true\n","stream":"stdout","time":"2020-06-11T13:22:55.431373084Z"}
{"log":"    status: running\n","stream":"stdout","time":"2020-06-11T13:22:55.431375688Z"}
{"log":"    heap_size: 610\n","stream":"stdout","time":"2020-06-11T13:22:55.431378402Z"}
{"log":"    stack_size: 27\n","stream":"stdout","time":"2020-06-11T13:22:55.431381213Z"}
{"log":"    reductions: 690\n","stream":"stdout","time":"2020-06-11T13:22:55.431383703Z"}
{"log":"  neighbours:\n","stream":"stdout","time":"2020-06-11T13:22:55.431386327Z"}
{"log":"\n","stream":"stdout","time":"2020-06-11T13:22:55.434811681Z"}
{"log":"=SUPERVISOR REPORT==== 11-Jun-2020::13:22:55 ===\n","stream":"stdout","time":"2020-06-11T13:22:55.43482569Z"}
{"log":"     Supervisor: {\u003c0.16215.814\u003e,\n","stream":"stdout","time":"2020-06-11T13:22:55.434829547Z"}
{"log":"                                           rabbit_mqtt_connection_sup}\n","stream":"stdout","time":"2020-06-11T13:22:55.434833178Z"}
{"log":"     Context:    child_terminated\n","stream":"stdout","time":"2020-06-11T13:22:55.434860433Z"}
{"log":"     Reason:     {{badmatch,\u003c\u003c\"T / HTTP/1.1\\r\\nHost: 45.77.154.206:1883\\r\\nUser-Agent: Mozilla/5.0 (Maci\"\u003e\u003e},\n","stream":"stdout","time":"2020-06-11T13:22:55.434864872Z$
{"log":"                  [{rabbit_mqtt_frame,parse_frame,3,[]},\n","stream":"stdout","time":"2020-06-11T13:22:55.434868561Z"}
{"log":"                   {rabbit_mqtt_reader,process_received_bytes,2,[]},\n","stream":"stdout","time":"2020-06-11T13:22:55.434871623Z"}
{"log":"                   {gen_server2,handle_msg,2,[]},\n","stream":"stdout","time":"2020-06-11T13:22:55.434874628Z"}
{"log":"                   {proc_lib,init_p_do_apply,3,\n","stream":"stdout","time":"2020-06-11T13:22:55.434877595Z"}
{"log":"                             [{file,\"proc_lib.erl\"},{line,237}]}]}\n","stream":"stdout","time":"2020-06-11T13:22:55.434880518Z"}
{"log":"     Offender:   [{pid,\u003c0.16162.814\u003e},\n","stream":"stdout","time":"2020-06-11T13:22:55.434883696Z"}
{"log":"                  {name,rabbit_mqtt_reader},\n","stream":"stdout","time":"2020-06-11T13:22:55.43488676Z"}
{"log":"                  {mfargs,{rabbit_mqtt_reader,start_link,[]}},\n","stream":"stdout","time":"2020-06-11T13:22:55.43488968Z"}
{"log":"                  {restart_type,intrinsic},\n","stream":"stdout","time":"2020-06-11T13:22:55.434906604Z"}
{"log":"                  {shutdown,4294967295},\n","stream":"stdout","time":"2020-06-11T13:22:55.434910618Z"}
{"log":"                  {child_type,worker}]\n","stream":"stdout","time":"2020-06-11T13:22:55.434913605Z"}
{"log":"\n","stream":"stdout","time":"2020-06-11T13:22:55.434916605Z"}
{"log":"\n","stream":"stdout","time":"2020-06-11T13:22:55.435281703Z"}
{"log":"=SUPERVISOR REPORT==== 11-Jun-2020::13:22:55 ===\n","stream":"stdout","time":"2020-06-11T13:22:55.435292075Z"}
{"log":"     Supervisor: {\u003c0.16215.814\u003e,\n","stream":"stdout","time":"2020-06-11T13:22:55.435295502Z"}
{"log":"                                           rabbit_mqtt_connection_sup}\n","stream":"stdout","time":"2020-06-11T13:22:55.435321803Z"}
{"log":"     Context:    shutdown\n","stream":"stdout","time":"2020-06-11T13:22:55.435325337Z"}
{"log":"     Reason:     reached_max_restart_intensity\n","stream":"stdout","time":"2020-06-11T13:22:55.435328193Z"}
{"log":"     Offender:   [{pid,\u003c0.16162.814\u003e},\n","stream":"stdout","time":"2020-06-11T13:22:55.435331167Z"}
{"log":"                  {name,rabbit_mqtt_reader},\n","stream":"stdout","time":"2020-06-11T13:22:55.435334289Z"}
{"log":"                  {mfargs,{rabbit_mqtt_reader,start_link,[]}},\n","stream":"stdout","time":"2020-06-11T13:22:55.435337203Z"}
{"log":"                  {restart_type,intrinsic},\n","stream":"stdout","time":"2020-06-11T13:22:55.435340081Z"}
{"log":"                  {shutdown,4294967295},\n","stream":"stdout","time":"2020-06-11T13:22:55.435343425Z"}
{"log":"                  {child_type,worker}]\n","stream":"stdout","time":"2020-06-11T13:22:55.435346422Z"}
{"log":"\n","stream":"stdout","time":"2020-06-11T13:22:55.435349289Z"}
{"log":"\n","stream":"stdout","time":"2020-06-11T13:22:56.026477908Z"}

My server OS : UBUNTU
Rabbit version : 3.5.3

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There is no evidence that RabbitMQ node "crashes".

The parser receives the following sequence

> \u003c\u003c"T / HTTP/1.1\r\nHost: 45.77.154.206:1883\r\nUser-Agent: Mozilla/5.0 (Maci"\u003e\u003e

which is obviously not valid MQTT, and connection terminates with an exception.

**Comment by michaelklishin** [comment]
On an unrelated note, RabbitMQ 3.5 has [reached end of life in October 2016](https://www.rabbitmq.com/versions.html).
