### ISSUE TITLE
Consider making subscription_ttl optional

### ISSUE THREAD

**Issue by et1975** [rabbitmq/rabbitmq-mqtt#26]
Mandatory queue TTL violates qos1 expectations and since the messages themselves are not expired makes the situation difficult to resolve correctly.

**Comment by michaelklishin** [comment]
You already can [set it to undefined](https://github.com/rabbitmq/rabbitmq-mqtt/blob/master/src/rabbit_mqtt_processor.erl#L471-478).

We can consider changing the default. The problem is that some clients will never unsubscribe and leave queues behind.
