### ISSUE TITLE
Question re: TLS Session Resumption supported?

### ISSUE THREAD

**Issue by mikeatlas** [rabbitmq/rabbitmq-mqtt#29]
Hi,

How, if it all, does RabbitMQ (and/or RabbitMQ MQTT plugin) support TLS Session Resumption? 

One of the challenges of keeping bandwidth and battery overhead low on IoT-scale devices (the whole point of MQTT) is that TLS handshakes are high overhead - and thus TLS Session Resumption is the resolution to avoid repeated TLS handshakes in an MQTT session.

[HiveMQ claims they offer TLS Session Resumption](http://www.hivemq.com/mqtt-security-fundamentals-tls-ssl/) to avoid repeat-handshake overhead to keep MQTT long-term session overhead low, but others will claim that [TLS Session Resumption also opens your client up for attacks unless you're doing correct Perfect Forward Secrecy](https://timtaubert.de/blog/2014/11/the-sad-state-of-server-side-tls-session-resumption-implementations/).

I couldn't find anything on Google about Rabbit's TLS implementation (or rabbitmq-mqtt) with regards to the [MQTT 3.1.1 OASIS](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html) spec, which does reference _TLS Session Resumption_:
> [RFC5077]
Salowey, J., Zhou, H., Eronen, P., and H. Tschofenig, "Transport Layer Security (TLS) Session Resumption without Server-Side State", RFC 5077, January 2008.
http://www.ietf.org/rfc/rfc5077.txt

Lastly, someone challenged some [MQTT-over-TLS benchmarked versus HTTPS](http://stephendnicholas.com/archives/1217) (see [comment 1173 by Hannes Tschofenig](http://stephendnicholas.com/archives/1217#comment-1173)) as invalid without describing what means and methods of TLS were used for the tests. I tend to agree and would like to know more, if possible. 

Thanks!
Mike

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users in the future.

RabbitMQ does not implement TLS, the Erlang  runtime and standard library does. I couldn't find much about whether it supports RFC 5077. This is a good question for [erlang-questions](http://erlang.org/mailman/listinfo/erlang-questions).

Users who need less commonly used TLS extensions want to run Erlang 17.x or 18.

**Comment by mikeatlas** [comment]
Will do. Thanks

**Comment by mikeatlas** [comment]
I may just use http://hackersome.com/p/vincentbernat/rfc5077 / https://github.com/vincentbernat/rfc5077 one of these clients against CloudAMQP's TLS endpoints and verify here for posterity the results.

**Comment by michaelklishin** [comment]
:+1: — we would be interested in knowing what comes out of your testing!

**Comment by mikeatlas** [comment]
Well, I could have dug further. RabbitMQ is built off Erlang, which is built off OpenSSL `0.9.7 or higher`. For OpenSSL, as of `OpenSSL 0.9.8f`, RFC4507bis support was added (which was superseded by RFC 5077).

Regardless, I found the `[sslyze](https://github.com/nabla-c0d3/sslyze/releases)` tool, and this output [full pastebin](http://pastebin.com/Kgz5nRgp) indicates some good news when run against CloudAMQP, who host [RabbitMQ+MQTT with TLS](https://www.cloudamqp.com/docs/mqtt.html).

```
* Session Resumption:
   With Session IDs: OK - Supported (5 successful, 0 failed, 0 errors, 5 total attempts).
   With TLS Session Tickets: NOT SUPPORTED - TLS ticket not assigned.
```
So, question answered! I just really had to dig. Now... to find out if the MQTT clients I'm going to use support it... is another question.

**Comment by mikeatlas** [comment]
I suppose you could tout this in your documentation ;)

**Comment by michaelklishin** [comment]
@mikeatlas this is the first time this topic was brought up, in many years that TLS is supported.

Note that Erlang does not use OpenSSL for TLS state machines, negotiation, etc. OpenSSL is limited to a crypto function library. So inspecting OpenSSL version capabilities is only worth so much. Testing with tools such as `sslyze` is a much more reliable way :)

Thank you for taking the time and reporting back!

**Comment by mikeatlas** [comment]
Indirectly, thanks for ClojureWerkz. We a handful of your libraries heavily, I just noticed the connection.

**Comment by michaelklishin** [comment]
@mikeatlas happy that you find them useful!
