### ISSUE TITLE
Retained messages in RabbitMQ 3.5.4

### ISSUE THREAD

**Issue by jpvdmerwe** [rabbitmq/rabbitmq-mqtt#31]
Hi,

I am trying to publish retained messages using the M2MQtt C# library however it seems that RabbitMQ is not retaining them.

Has this been developed?

Kind Regards,
JP

**Comment by videlalvaro** [comment]
Retained messages are already implemented, but will be part of the 3.6.x release. Also, please ask this kind of questions on our mailing list: https://groups.google.com/forum/#!forum/rabbitmq-users

**Comment by michaelklishin** [comment]
The issue you're after is https://github.com/rabbitmq/rabbitmq-mqtt/issues/16.
