### ISSUE TITLE
Bridging to/from Mosquitto.

### ISSUE THREAD

**Issue by mkarliner** [rabbitmq/rabbitmq-mqtt#34]
I've just be trying to set up a mosquitto bridge to the rabbitmq mqtt plugin.
The configuration works fine to another mosquitto, but so far I'm 
unable to connect to your plugin. Is this even supposed to be possible?

BTW the motivation for doing this is to work around the lack of websocket
support in the current plugin

**Comment by michaelklishin** [comment]
Questions belong to rabbitmq-users. We haven't tried using Mosquitto bridge.
If someone provides code examples and error more specific than "unable to connect", we would be happy see what can be improved.

And RabbitMQ log files, too.

WebSocket support is coming as a separate plugin around November, if all goes well.

**Comment by mkarliner** [comment]
My apologies for asking in the wrong place. I merely wanted to know if the plugin was
supposed to support bridging before I bothered you with the details of my specific
problem. Obviously, if I wanted to help to debug, I would provide more than 'can't connect' :-)

Mike

**Comment by mkarliner** [comment]
Oh and FWIW, Mosquitto<->Rabbit MQTT does work. Here's an extract from my mosquitto.conf for the approximate incantation.

log_type debug
connection Rabbit
try_private false
address 192.168.10.195
bridge_attempt_unsubscribe false
bridge_protocol_version mqttv311
bridge_insecure true
topic # both 2 local/sensor/ remote/sensor/

**Comment by michaelklishin** [comment]
Given that Mosquitto uses a standard MQtT 3.1.1 client, we'd be happy to support bridging with it.

**Comment by ajaykumarkerur** [comment]
Hi Michael/Michael Klishin,
                   I am trying to bridge between Mosquitto1.3.4 (which is installed in raspberry Pi) and RabbitMQ 3.5.6 (Which is installed in Desktop with Ubuntu16.04 OS) both are in the same network.
I am facing the below issue.
Whenever I publish on some topic in Raspberry Pi, client Subscribed for rabbitMQ(for the same topic) are not getting the published message.
Can you share us how did you do bridging of ,one mosquitto with other.
  
I am trying to achieve what is mentioned in the below link. 
http://blog.jonharrington.org/displaying-mqtt-messages-in-a-browser-in-real-time/
Kindly guide us,how to proceed.

Thanks in advance.
Ajay

**Comment by michaelklishin** [comment]
@ajaykumarkerur I do not have any advice for you. Please post your questions to rabbitmq-users.

**Comment by ajaykumarkerur** [comment]
Thank you for the information

**Comment by twooster** [comment]
For anyone who comes across this in the future, the answer is almost certainly `try_private`. Mosquitto uses a nonstandard high-bit to indicate that it's operating in "broker" mode on bridge connections. RabbitMQ's MQTT plugin doesn't like this bit, and so drops the connection. So make sure:

```
try_private false
```
Is set in your mosquitto configuration.

**Comment by michaelklishin** [comment]
@twooster thank you very much. We will consider adding a note to the documentation guide.

**Comment by ralienpp** [comment]
2 years later I stumbled upon this,  I confirm that `try_private false`, and there is no mention of it in the RabbitMQ docs.

I understand that having this in the RabbitMQ doc is somewhat controversial, because it is about a quirk of a protocol deviation in Mosquitto, not exactly RabbitMQ's problem. Nevertheless, including this remark could save other people's time.

**Comment by michaelklishin** [comment]
You are welcome to add a bridging section to the [MQTT guide](https://github.com/rabbitmq/rabbitmq-website/blob/live/site/mqtt.md). The website is open source.

**Comment by mkarliner** [comment]
Gosh, I'd completely forgotten about my OP.
Thanks folks for keeping with it and finding a solution/answer.

Mike
