### ISSUE TITLE
Don't log connection error for tcp health check

### ISSUE THREAD

**Issue by ljolin** [rabbitmq/rabbitmq-mqtt#36]
The error log is filled with "MQTT detected network error" because of the load balancers health checks. Could you (as it has been done for the amqp plugin) prevent error logging when no data is sent between  connection and disconnection (see : https://groups.google.com/forum/#!topic/rabbitmq-users/h1wGglkVvZQ)

**Comment by michaelklishin** [comment]
Good idea, thank you.
