### ISSUE TITLE
Standalone build fails because warnings are treated as errors

### ISSUE THREAD

**Issue by gotthardp** [rabbitmq/rabbitmq-mqtt#41]
compile: warnings being treated as errors
src/rabbit_mqtt_processor.erl:465: this clause cannot match because a previous clause at line 464 always matches
erlang.mk:4961: recipe for target 'ebin/rabbitmq_mqtt.app' failed
make[1]: *** [ebin/rabbitmq_mqtt.app] Error 1

**Comment by michaelklishin** [comment]
We are aware of this issue but it is only relevant when you try to build this repo alone. When building a release as part of the umbrella, it is treated as a dependency of `rabbit`, and warnings are not treated as errors for dependencies.

Fixing the warning is trivial and requires more consideration than re-arranging a couple of lines.

**Comment by essen** [comment]
FYI: This is still an issue, and also in rabbitmq-stomp.
