### ISSUE TITLE
Cannot connect with cleansession=false when previous connection had cleansession=true

### ISSUE THREAD

**Issue by lokewate** [rabbitmq/rabbitmq-mqtt#47]
I had written some code to connect to the MQTT broker using the default value for cleansession, which was true using the Paho golang package. When I changed this to have cleansession=false, the client failed to connect to the broker. However, when I tried doing the same with test.mosquitto.org, things work fine. I am using RabbitMQ 3.5.6, Erlang 18.1

You can find details of the error and the code here:
http://stackoverflow.com/questions/34038284/mqtt-change-client-from-using-cleanstate-true-to-cleanstate-false

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users.

See broker log files. Most likely this is due to #30 which was corrected #37. But it can also be due to queue attribute mismatch: delete the queue for your subscription in the management UI first. Again, log files will give you a clue.
