### ISSUE TITLE
Change default queue TTL to 1 day

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-mqtt#49]
It is currently too short.

The reason why we have it at all is because without Clean Session set on a connection, its client can go away and never come back at any moment, and we'd have durable queues with persistent messages sitting around forever.

This can be confusing and now is a good time to revisit the default.

**Comment by videlalvaro** [comment]
:+1:

**Comment by hairyhum** [comment]
As I understand it can be decreased only, so it's kind of 'maximum TTL', or not?

**Comment by michaelklishin** [comment]
@hairyhum it can be disabled entirely. That's not a range, just a fixed value, like all TTLs.

**Comment by michaelplaing** [comment]
FYI the default in mosquitto is 'disabled'.

Regardless of the setting, new users will collide with this.

'disabled' will avoid data loss at the risk of many posts to the list
asking how to clean up the queues :)

**Comment by hairyhum** [comment]
@michaelklishin ok

**Comment by michaelklishin** [comment]
@michaelplaing thank you for the data point. I completely agree. "1 day" may be a decent middle ground.

**Comment by michaelklishin** [comment]
OK, one downside of this is one time upgrade pains for those who don't disable or override TTL. But this still feels like the right thing to do — the old default is fairly dangerous.
