### ISSUE TITLE
SessionPresent flag not set when reconnected to server

### ISSUE THREAD

**Issue by AndrewJarmanTI** [rabbitmq/rabbitmq-mqtt#61]
Tested using RabbitMQ 3.6.0.  It was recently installed and uses default settings.

When connecting to a server with cleansession=0 and a valid client-id, a persistent session should be created.  

I captured the packet response using tcpdump, and found the "CONACK" response.  This eliminates the client as a factor.

The packet after the CON returned: "0x20 0x02 0x00 0x00"
0x20 = CONACK type
0x02 = remaining bytes in message == 2
0x00 = Connect Acknowledge flags.  Bit 0 should be set.
0x00 = Connect Return Code.

It should have the values:
"0x20 0x02 0x01 0x00"
0x20 = CONACK type
0x02 = remaining bytes in message == 2
0x00 = Connect Acknowledge flags.  Bit 0 indicating session present.
0x00 = Connect Return Code.

I have verified with a test program that this works.  I have also tested this same program against iot.eclipse.org and test.mosquitto.org and it works as expected.

In all other ways, the MQTT plugin is working as expected.  The persistent queue is created using the client-id, and QoS1 messages delivered to an existing subscription are queuing up as shown in the management console.  Also, when the client connects it does receive the queued messages.  The only issue is the SessionPresent flag isn't being reported properly.

**Comment by michaelklishin** [comment]
So what exactly are the steps we should use to reproduce?

**Comment by AndrewJarmanTI** [comment]
Attached 2 packet captures.  Mosquitto.txt has a capture from a public running Mosquitto MQTT broker, while the rabbitmq.txt has a capture from an install of RabbitMQ 3.6.0 on a test Linux server we have running in the cloud.

My test client is an embedded system running the org.eclipse.paho.mqtt.embedded-c library.  I was able to capture the packets on a Linux system acting as a router.

You should be able to reproduce the symptoms on any MQTT client.  It is hard to tell if the client opened the connection and received a Session Preset == true on many of the tools, that's why I used the packet capture to test at the wire level.

My test sequence was:

1. Connect to the server with a client-id (use a new one that hasn't been seen on the server).
  - inspect the packet response to see if the Session Present bit was set.
2. Publish to a topic using QoS1.
3. Close the connection.

repeat sequence above using the same client-id.  The Session Present flag should be set now.

If you are able to fix it and need somebody to confirm the fix, let me know and provide a URL to a reachable address.

[rabbitmq.txt](https://github.com/rabbitmq/rabbitmq-mqtt/files/148991/rabbitmq.txt)
[mosquitto.txt](https://github.com/rabbitmq/rabbitmq-mqtt/files/148992/mosquitto.txt)

**Comment by HW-Siew** [comment]
Confirmed the same behavior on RabbitMQ 3.6.1. The session present flag should be set to 1 in CONNACK packet when clean session flag is set to 0 in CONNECT packet. http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718033

**Comment by hairyhum** [comment]
@AndrewJarmanTI can you confirm that session is not being cleared and works as expected for resuming session?

**Comment by AndrewJarmanTI** [comment]
Unfortunately I am not in a position right now to build and test rabbitmq from source.  Another group is running the server, they installed from binaries, and are not available right now to compile and provision another instance.
If there is an instance with this fix running somewhere on a public IP, I can connect to it from my client and verify if that helps.

**Comment by michaelklishin** [comment]
@AndrewJarmanTI no worries, it should be fairly easy to reproduce for us. Thank you.
