### ISSUE TITLE
Generic server terminating

### ISSUE THREAD

**Issue by scnets** [rabbitmq/rabbitmq-mqtt#70]
RabbitMQ is terminating and we can't figure out why.  I can reproduce this issue almost every time using the Paho MQTT Java client.  Here's the Java code and I've attached the log file.  Any help on this issue would be appreciated. Thanks, Chris

More information can be found in this forums thread.
https://groups.google.com/forum/#!topic/rabbitmq-users/frm5TShQW-0

**Comment by michaelklishin** [comment]
```

=ERROR REPORT==== 6-Feb-2016::14:23:50 ===
** Generic server <0.3687.0> terminating
** Last message in was {inet_async,#Port<0.25554>,2834,
                           {ok,<<"GET / HTTP/1.1\r\nHost: 192.168.86.104:1883\r\nConnection: keep-alive\r\nAccept: 
```

Something connects to port 1883 and posts HTTP requests.
