### ISSUE TITLE
When authenticating using a client cert, there is no way to specify a vhost for that client

### ISSUE THREAD

**Issue by pickettphil** [rabbitmq/rabbitmq-mqtt#73]
When connecting with username/password, vhost is specified as part of username (vhost:username), but there is no username when authenticating with a client cert. Is there some way to tie a vhost to a user using client cert authentication?

Some possible solutions are:

1) Use the x509 certificate's optional fields. This could be problematic for many users.
2) Provide a mapping of user (via client cert) to vhost via runtime parameters.

**Comment by michaelklishin** [comment]
We are investigating this for `3.6.7`.

**Comment by michaelklishin** [comment]
Merged into `stable`, needs merging into master (and porting CLI changes to the new CLI repo).
