### ISSUE TITLE
Loopback publish issue with mosquitto after bridged

### ISSUE THREAD

**Issue by dennislwy** [rabbitmq/rabbitmq-mqtt#83]
I have two mosquitto brokers installed on PC1 (mosquitto v1.4.8) and PC2 (RabbitMQ v3.6.2 with MQTT Adapter).  
Bridging initiated at PC1 like this:  `sensor/room1/ <-> office/room1/`  
But I noticed there is always a duplicate message being published back whenever the bridge is active, means all my application (on PC1) which subscribes to the same topic will receives the same message twice  

Please have a look at the question i posted in [Stackoverflow](http://stackoverflow.com/questions/37607629/how-to-prevent-loopback-publish-in-bridged-mqtt-brokers). I having no issue if bridged to another mosquitto broker with `try_private true` in mosquitto.conf

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.
