### ISSUE TITLE
MQTT Interoperability tests @ Eclipsecon

### ISSUE THREAD

**Issue by andypiper** [rabbitmq/rabbitmq-mqtt#9]
RabbitMQ fails initial MQTT Interop test with:

`
MQTT detected framing error "127.0.0.1:50997 -> 127.0.0.1:1883" for connection protocol_header_corrupt
`

-> this is due to the tests using v3.1.1 of the protocol (which uses a header of MQTT instead of MQIsdp, and 4 instead of 3 as the broker)

Source for interop tests available here:
http://wiki.eclipse.org/Interop_Testing_Plan

**Comment by hiteshjoshi** [comment]
I am getting this error on 3.2.4 , 


=INFO REPORT==== 16-Jan-2015::07:58:40 ===
accepting MQTT connection (182.68.248.241:62230 -> 128.199.184.52:1883)

=ERROR REPORT==== 16-Jan-2015::07:58:40 ===
MQTT detected framing error "182.68.248.241:62230 -> 128.199.184.52:1883" for connection protocol_header_corrupt


Trying to just login with nodejs mqtt driver

**Comment by carlhoerberg** [comment]
@hiteshjoshi upgrade to >=3.3.5
