### ISSUE TITLE
Standalone build fails with `behaviour ranch_protocol undefined`

### ISSUE THREAD

**Issue by michaesc** [rabbitmq/rabbitmq-mqtt#92]
It seems there is a dependency to ranch that causes a standard plugin build to fail (in both rabbit-stomp and rabbit-mqtt) during build:

```
$ git clone https://github.com/rabbitmq/rabbitmq-mqtt.git && cd rabbitmq-mqtt && make
[...]
...error is: compile: warnings being treated as errors21:33:31
src/rabbit_mqtt_connection_sup.erl:20: behaviour ranch_protocol undefined21:33:41
erlang.mk:4971: recipe for target 'ebin/rabbitmq_mqtt.app' failed21:33:59
make[1]: *** [ebin/rabbitmq_mqtt.app] Error 1
```

**Comment by michaesc** [comment]
Should we close this #92 since it seems to be a duplicate (in logic at least) of #90?

**Comment by michaesc** [comment]
By the way, when stating 'number-sign ninety' I meant:

https://github.com/rabbitmq/rabbitmq-stomp/issues/90

...although github rewrote the number to refer to a bug in this same MQTT repository.

**Comment by michaelklishin** [comment]
Closing per suggestion above (effectively the same issue is already filed for rabbitmq/rabbitmq-stomp).
