### ISSUE TITLE
MQTT Client reconnect after unsubscribe is creating queue again

### ISSUE THREAD

**Issue by khatwaniNikhil** [rabbitmq/rabbitmq-mqtt#94]
Scenario Steps:

1) MQTT client subscribe for topic "t" (server side subscription ttl defined 30 secs)
2) Disconnect MQTT client
3) Susbcription expire after ttl (queue and binding are getting deleted)
4) MQTT client reconnects only (no subscription)
5) no queue & binding should be created **but queue is getting created**.

I am attaching the MqttTest.java (same java file as present in rabbitmq-mqtt github, added method "testMQTTSubUnSubQueueCreationOnReconnect".
[Uploading MqttTest.java.zip…]()

**Comment by michaelklishin** [comment]
I suspect that what you want is to connect with a clear session. This is a discussion for rabbitmq-users, there is no evidence that this is a plugin problem. Your code archive didn't attach, too.

**Comment by michaelklishin** [comment]
Indeed, there are two cases where queues are declared:

 * Client sends a `SUBSCRIBE` frame
 * Client connects with `clean session = false` and a client id

**Comment by khatwaniNikhil** [comment]
Sorry, I didn't understood queue creation on "Client connects with clean session = false and a client id". 
I have posted to google group, can you please take out time and have a look at https://groups.google.com/forum/#!topic/rabbitmq-users/GpUWc92uep8
