### ISSUE TITLE
Login with a valid username and an empty password succeeds if TLS isn't used

### ISSUE THREAD

**Issue by msschwartz** [rabbitmq/rabbitmq-mqtt#96]
Connection succeeds when password is left blank for users with password set. I've experienced this issue on versions 3.4.3 and 3.6.4. 

Using ```{allow_anonymous,  false}``` doesn't change the outcome.

**Comment by msschwartz** [comment]
Also, I noticed the testInvalidPassword() test case is very similar to testInvalidUser(). It doesn't really test an invalid password.

**Comment by michaelklishin** [comment]
I cannot reproduce this so please move it to the mailing list:

```
2.3.1 :003 >   c = MQTT::Client.connect('127.0.0.1', username: "guest", password: "")
MQTT::ProtocolException: Connection refused: bad user name or password
	from /Users/antares/Development/RabbitMQ/ruby-mqtt.git/lib/mqtt/client.rb:498:in `block in receive_connack'
	from /Users/antares/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /Users/antares/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /Users/antares/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /Users/antares/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /Users/antares/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /Users/antares/Development/RabbitMQ/ruby-mqtt.git/lib/mqtt/client.rb:488:in `receive_connack'
	from /Users/antares/Development/RabbitMQ/ruby-mqtt.git/lib/mqtt/client.rb:276:in `connect'
	from /Users/antares/Development/RabbitMQ/ruby-mqtt.git/lib/mqtt/client.rb:93:in `connect'
	from (irb):3
	from /Users/antares/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
2.3.1 :004 > c = MQTT::Client.connect('127.0.0.1', username: "guest", password: "guest")
 => #<MQTT::Client:0x007f94b238e6b0 @host="127.0.0.1", @port=1883, @version="3.1.0", @keep_alive=15, @clean_session=true, @client_id="rubyawh1igfqp8h3482w", @ack_timeout=5, @username="guest", @password="guest", @will_topic=nil, @will_payload=nil, @will_qos=0, @will_retain=false, @ssl=false, @last_ping_request=2016-08-30 00:18:10 +0300, @last_ping_response=2016-08-30 00:18:10 +0300, @socket=#<TCPSocket:fd 10>, @read_queue=#<Thread::Queue:0x007f94b238de40>, @read_thread=#<Thread:0x007f94b118b120@/Users/antares/Development/RabbitMQ/ruby-mqtt.git/lib/mqtt/client.rb:279 sleep>, @write_semaphore=#<Thread::Mutex:0x007f94b238ddc8>>
```

**Comment by michaelklishin** [comment]
We need your exact config and a code snippet to reproduce. Please post them to rabbitmq-users. Thank you.

**Comment by msschwartz** [comment]
I'm going to add this to the mailing list. Just an fyi, when I added the ```{allow_anonymous,  false}```, the empty passwords started working again. So that argument is causing the issue.

**Comment by msschwartz** [comment]
@michaelklishin Sorry to bother you, but can you try this instead:
```c = MQTT::Client.connect('127.0.0.1', username: "guest")```
rather than
```c = MQTT::Client.connect('127.0.0.1', username: "guest", password: "")```

I see the same result as you when providing an empty password. I guess it has to be null or missing completely. I should have been more clear in my description.

Most likely you will see the "MQTT login failed for "guest" access_refused (access must be from localhost)" so try using a different user.

**Comment by michaelklishin** [comment]
I can try that. My example is executed from a local REPL.

**Comment by michaelklishin** [comment]
This [mailing list thread](https://groups.google.com/forum/#!topic/rabbitmq-users/9zva7zFfoGc) provides a specific config and code example => we now have something to work with and this issue is potentially important enough to investigate.

**Comment by michaelklishin** [comment]
This was back ported to `3.5.x` and will be in `3.5.8` (currently the final `3.5.x` series release planned).
